name: "OpenVPN Client"
version: "1.0.4.0"
slug: "openvpn_client"
description: "A secure way to send your data through any OpenVPN Server"
url: "https://github.com/rofra/homeassistant-openvpn-client-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
init: false
boot: auto
host_network: true
privileged:
  - NET_ADMIN
options:
  ovpncontent: |
    This example is an example of literal block scalar style in YAML.
    It allows you to split a string into multiple lines.
  ovpnpass: ""
  username: ""
  password: ""
  customargs: ""
schema:
  ovpncontent: str
  ovpnpass: password?
  username: str?
  password: password?
  customargs: str?
map:
  - config:ro